# Generated by Django 3.0.5 on 2021-03-26 03:22

from django.db import migrations, models
import django.db.models.deletion
import farm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambient_data_date', models.DateTimeField(auto_now_add=True)),
                ('ambient_humidity', models.FloatField(validators=[farm.models.validate_humidity])),
                ('ambient_light_intensity', models.FloatField()),
                ('ambient_temperature', models.FloatField(validators=[farm.models.validate_temperature])),
            ],
        ),
        migrations.CreateModel(
            name='SeedContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_container_degree', models.FloatField(validators=[farm.models.validate_degree])),
                ('seed_container_radius', models.FloatField(validators=[farm.models.validate_radius])),
                ('seed_container_level', models.IntegerField(choices=[(0, 'Service Level'), (1, 'Plant Level 1'), (2, 'Plant Level 2'), (3, 'Plant Level 3'), (4, 'Plant Level 4')], default=1, validators=[farm.models.validate_level])),
            ],
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type_name', models.CharField(max_length=255)),
                ('growing_radius', models.FloatField(default=2.0, validators=[farm.models.validate_radius])),
                ('desired_humidity', models.FloatField(default=30.0, validators=[farm.models.validate_humidity])),
                ('desired_light_red', models.IntegerField(default=150, validators=[farm.models.validate_light])),
                ('desired_light_green', models.IntegerField(default=150, validators=[farm.models.validate_light])),
                ('desired_light_blue', models.IntegerField(default=150, validators=[farm.models.validate_light])),
                ('desired_temperature', models.FloatField(default=25.0, validators=[farm.models.validate_temperature])),
                ('seed_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.SeedContainer')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(blank=True, default='plant', max_length=255)),
                ('degree', models.FloatField(validators=[farm.models.validate_degree])),
                ('radius', models.FloatField(validators=[farm.models.validate_radius])),
                ('level', models.IntegerField(choices=[(0, 'Service Level'), (1, 'Plant Level 1'), (2, 'Plant Level 2'), (3, 'Plant Level 3'), (4, 'Plant Level 4')], default=1, validators=[farm.models.validate_level])),
                ('harvested', models.BooleanField(default=False)),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.PlantType'))
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('WT', 'Watering Task'), ('SD', 'Seeding Task'), ('PD', 'Plant Data Gathering Task'), ('AD', 'Ambient Data Gathering Task'), ('MC', 'Manual Control Task'), ('LC', 'Lighting Control Task')], max_length=2)),
                ('task_date', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Plant')),
            ],
        ),
        
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_data_date', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.FloatField(validators=[farm.models.validate_humidity])),
                ('plant', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='farm.Plant')),
            ],
        ),
    ]
