# Generated by Django 3.0.5 on 2021-03-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambientdata',
            old_name='ambient_data_date',
            new_name='ambient_data_date_time',
        ),
        migrations.RenameField(
            model_name='plantdata',
            old_name='plant_data_date',
            new_name='plant_data_date_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_date',
            new_name='task_date_time',
        ),
        migrations.AddField(
            model_name='plant',
            name='planted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('QED', 'Task Queued'), ('EXE', 'Executing'), ('FIN', 'Task Finished'), ('FAL', 'Task Failed')], default='QED', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Plant'),
        ),
    ]
